/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description 200 when the analyst is warm, else 503 (holds LB traffic). Never forces a build.
         */
        get: operations["ready_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyst/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyst Stream
         * @description Server-Sent Events stream of an analyst narration.
         *
         *     Event types:
         *         start      — { mode, model_id, scenario_id }
         *         token      — { text } (whitespace-split, paced by rate_tps)
         *         citations  — { citations[], cached, fell_back, model_id, prompt_version }
         *         done       — { total_tokens, gen_ms } (gen_ms = real LLM wall-time, not playback)
         *         error      — { message }
         */
        post: operations["analyst_stream_api_v1_analyst_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pipeline */
        post: operations["pipeline_api_v1_pipeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Qa */
        post: operations["qa_api_v1_qa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/education": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scenario Education
         * @description Static (no LLM) education entry for a wave family.
         */
        get: operations["scenario_education_api_v1_scenario_education_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario/layer1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Layer1 */
        post: operations["scenario_layer1_api_v1_scenario_layer1_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlternativeBriefOut */
        AlternativeBriefOut: {
            /** Direction */
            direction: string | null;
            /** Family */
            family: string;
            /** Family Label */
            family_label: string;
            invalidation: components["schemas"]["PriceMoveOut"] | null;
            /** Stage */
            stage: string;
            target_high: components["schemas"]["PriceMoveOut"] | null;
            target_low: components["schemas"]["PriceMoveOut"] | null;
        };
        /** AnalystStreamRequest */
        AnalystStreamRequest: {
            /**
             * Atr Floor
             * @default 0.1
             */
            atr_floor: number;
            /**
             * Atr Multiplier
             * @default 3
             */
            atr_multiplier: number;
            /**
             * Atr Period
             * @default 14
             */
            atr_period: number;
            /**
             * Commitment Curve
             * @default linear
             * @enum {string}
             */
            commitment_curve: "linear" | "sqrt" | "off";
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
            /**
             * K Sigma
             * @default 0.5
             */
            k_sigma: number;
            /**
             * Log Tol Fib
             * @default 0.05
             */
            log_tol_fib: number;
            /**
             * Min Bars Between
             * @default 4
             */
            min_bars_between: number;
            /**
             * Mode
             * @default explanation
             * @enum {string}
             */
            mode: "explanation" | "outlook" | "risk" | "differentiator";
            /**
             * Period
             * @default max
             * @enum {string}
             */
            period: "2y" | "5y" | "10y" | "max";
            /**
             * Pivot Window
             * @default 2
             */
            pivot_window: number;
            /**
             * Pull Depth Hi
             * @default 0.618
             */
            pull_depth_hi: number;
            /**
             * Pull Depth Lo
             * @default 0.382
             */
            pull_depth_lo: number;
            /**
             * Pull Depth Tol
             * @default 0.15
             */
            pull_depth_tol: number;
            /**
             * Rate Tps
             * @default 40
             */
            rate_tps: number;
            /**
             * Scale Mode
             * @default linear
             * @enum {string}
             */
            scale_mode: "linear" | "log";
            /**
             * Scenario Id
             * @description Scenario.id from /api/pipeline
             */
            scenario_id: string;
            /**
             * Symbol
             * @description Ticker symbol (yfinance compatible)
             * @default DDOG
             */
            symbol: string;
            /**
             * Timeframe
             * @default week
             * @enum {string}
             */
            timeframe: "day" | "week" | "month";
        };
        /** BarOut */
        BarOut: {
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Time */
            time: string;
            /** Volume */
            volume: number;
        };
        /** BottleneckOut */
        BottleneckOut: {
            /** Dimension */
            dimension: string;
            /** Gap To Next */
            gap_to_next: number;
            /** Intermediates */
            intermediates: {
                [key: string]: unknown;
            };
            /** Is Dim Minimum */
            is_dim_minimum: boolean;
            /** Is Overall Minimum */
            is_overall_minimum: boolean;
            /** Plain Explanation */
            plain_explanation: string;
            /** Slot Name */
            slot_name: string;
            /** Slot Value */
            slot_value: number;
            theory_ref: components["schemas"]["TheoryRefOut"];
        };
        /** CitationsFrame */
        CitationsFrame: {
            /** Cached */
            cached: boolean;
            /** Citations */
            citations: components["schemas"]["QaCitation"][];
            /** Fell Back */
            fell_back: boolean;
            /** Model Id */
            model_id: string | null;
            /** Prompt Version */
            prompt_version: string | null;
        };
        /** ConfidenceTierOut */
        ConfidenceTierOut: {
            /** Key */
            key: string;
            /** Word */
            word: string;
        };
        /** ConfirmationLevelOut */
        ConfirmationLevelOut: {
            /** Condition */
            condition: string;
            /** Met */
            met: boolean;
            /** Name */
            name: string;
            /** Theory Page */
            theory_page: number;
            /** Triggered At Bar */
            triggered_at_bar: number | null;
        };
        /** ConfirmationReportOut */
        ConfirmationReportOut: {
            /** Family */
            family: string;
            /** Highest Met */
            highest_met: string | null;
            /** Is Applicable */
            is_applicable: boolean;
            /** Levels */
            levels: components["schemas"]["ConfirmationLevelOut"][];
            not_applicable_reason: components["schemas"]["NotApplicableReasonOut"] | null;
        };
        /** DecisionSummaryOut */
        DecisionSummaryOut: {
            /** Bar Interval */
            bar_interval: string | null;
            current: components["schemas"]["PriceMoveOut"] | null;
            /** Direction */
            direction: string | null;
            /** Horizon Bars */
            horizon_bars: number | null;
            /** Horizon Human */
            horizon_human: string | null;
            invalidation: components["schemas"]["PriceMoveOut"] | null;
            /** Open Wave Direction */
            open_wave_direction: string | null;
            /** Open Wave Start */
            open_wave_start: number | null;
            /** Risk Reward */
            risk_reward: number | null;
            /** Stage */
            stage: string;
            target_high: components["schemas"]["PriceMoveOut"] | null;
            target_low: components["schemas"]["PriceMoveOut"] | null;
            /** Wave Progress Pct */
            wave_progress_pct: number | null;
        };
        /** DiagnosticOut */
        DiagnosticOut: {
            /** Death Reason */
            death_reason: string;
            /** First Divergence Index */
            first_divergence_index: number;
            /** Last Alive Segment Index */
            last_alive_segment_index: number;
            /** Suggested Action */
            suggested_action: string;
        };
        /** DoneFrame */
        DoneFrame: {
            /** Gen Ms */
            gen_ms: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** EducationResponse */
        EducationResponse: {
            /** Family */
            family: string;
            /** One Line */
            one_line: string;
            /** Rules */
            rules: string[];
            /** Title */
            title: string;
            /** Visual Cues */
            visual_cues: string[];
        };
        /** ErrorFrame */
        ErrorFrame: {
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /** Layer1Request */
        Layer1Request: {
            /**
             * Atr Floor
             * @default 0.1
             */
            atr_floor: number;
            /**
             * Atr Multiplier
             * @default 3
             */
            atr_multiplier: number;
            /**
             * Atr Period
             * @default 14
             */
            atr_period: number;
            /**
             * Commitment Curve
             * @default linear
             * @enum {string}
             */
            commitment_curve: "linear" | "sqrt" | "off";
            /**
             * K Sigma
             * @default 0.5
             */
            k_sigma: number;
            /**
             * Log Tol Fib
             * @default 0.05
             */
            log_tol_fib: number;
            /**
             * Min Bars Between
             * @default 4
             */
            min_bars_between: number;
            /**
             * Period
             * @default max
             * @enum {string}
             */
            period: "2y" | "5y" | "10y" | "max";
            /**
             * Pivot Window
             * @default 2
             */
            pivot_window: number;
            /**
             * Pull Depth Hi
             * @default 0.618
             */
            pull_depth_hi: number;
            /**
             * Pull Depth Lo
             * @default 0.382
             */
            pull_depth_lo: number;
            /**
             * Pull Depth Tol
             * @default 0.15
             */
            pull_depth_tol: number;
            /**
             * Scale Mode
             * @default linear
             * @enum {string}
             */
            scale_mode: "linear" | "log";
            /**
             * Scenario Id
             * @description Scenario.id from /api/pipeline response
             */
            scenario_id: string;
            /**
             * Symbol
             * @description Ticker symbol (yfinance compatible)
             * @default DDOG
             */
            symbol: string;
            /**
             * Timeframe
             * @default week
             * @enum {string}
             */
            timeframe: "day" | "week" | "month";
        };
        /** Layer1Response */
        Layer1Response: {
            alternative: components["schemas"]["AlternativeBriefOut"] | null;
            bottleneck: components["schemas"]["BottleneckOut"] | null;
            confirmation: components["schemas"]["ConfirmationReportOut"] | null;
            decision: components["schemas"]["DecisionSummaryOut"] | null;
            /** Scenario Id */
            scenario_id: string;
            /** Score Intermediates */
            score_intermediates: {
                [key: string]: unknown;
            };
            succession: components["schemas"]["SuccessionReportOut"] | null;
            targets: components["schemas"]["TargetSetOut"] | null;
        };
        /** LinkSetOut */
        LinkSetOut: {
            /** Degree Label */
            degree_label: string | null;
            /** Leg End */
            leg_end: number;
            /** Leg Start */
            leg_start: number;
            /** Pattern Kind */
            pattern_kind: string;
            /** Pattern Label */
            pattern_label: string;
        };
        /** MetaOut */
        MetaOut: {
            config: components["schemas"]["PipelineConfigOut"];
            /** Generated At */
            generated_at: string;
            /** Period */
            period: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** NextPatternOut */
        NextPatternOut: {
            /** Link Band Far */
            link_band_far: number | null;
            /** Link Band Near */
            link_band_near: number | null;
            /** Link Type */
            link_type: string;
            /** Link Wave Size */
            link_wave_size: number | null;
            /** Next Families */
            next_families: string[];
            /** Rationale */
            rationale: string;
            /** Theory Pages */
            theory_pages: number[];
        };
        /** NotApplicableReasonOut */
        NotApplicableReasonOut: {
            /** Citation */
            citation: number | null;
            /** Text */
            text: string;
        };
        /** PipelineConfigOut */
        PipelineConfigOut: {
            /** Atr Floor */
            atr_floor: number;
            /** Atr Multiplier */
            atr_multiplier: number;
            /** Atr Period */
            atr_period: number;
            /** Commitment Curve */
            commitment_curve: string;
            /** K Sigma */
            k_sigma: number;
            /** Log Tol Fib */
            log_tol_fib: number;
            /** Min Bars Between */
            min_bars_between: number;
            /** Pivot Window */
            pivot_window: number;
            /** Pull Depth Hi */
            pull_depth_hi: number;
            /** Pull Depth Lo */
            pull_depth_lo: number;
            /** Pull Depth Tol */
            pull_depth_tol: number;
            /** Scale Mode */
            scale_mode: string;
        };
        /** PipelineRequest */
        PipelineRequest: {
            /**
             * Atr Floor
             * @default 0.1
             */
            atr_floor: number;
            /**
             * Atr Multiplier
             * @default 3
             */
            atr_multiplier: number;
            /**
             * Atr Period
             * @default 14
             */
            atr_period: number;
            /**
             * Commitment Curve
             * @default linear
             * @enum {string}
             */
            commitment_curve: "linear" | "sqrt" | "off";
            /**
             * K Sigma
             * @default 0.5
             */
            k_sigma: number;
            /**
             * Log Tol Fib
             * @default 0.05
             */
            log_tol_fib: number;
            /**
             * Min Bars Between
             * @default 4
             */
            min_bars_between: number;
            /**
             * Period
             * @default max
             * @enum {string}
             */
            period: "2y" | "5y" | "10y" | "max";
            /**
             * Pivot Window
             * @default 2
             */
            pivot_window: number;
            /**
             * Pull Depth Hi
             * @default 0.618
             */
            pull_depth_hi: number;
            /**
             * Pull Depth Lo
             * @default 0.382
             */
            pull_depth_lo: number;
            /**
             * Pull Depth Tol
             * @default 0.15
             */
            pull_depth_tol: number;
            /**
             * Scale Mode
             * @default linear
             * @enum {string}
             */
            scale_mode: "linear" | "log";
            /**
             * Symbol
             * @description Ticker symbol (yfinance compatible)
             * @default DDOG
             */
            symbol: string;
            /**
             * Timeframe
             * @default week
             * @enum {string}
             */
            timeframe: "day" | "week" | "month";
        };
        /** PipelineResponse */
        PipelineResponse: {
            /** Active Pivots */
            active_pivots: components["schemas"]["PivotOut"][];
            /** Bars */
            bars: components["schemas"]["BarOut"][];
            /** Load Error */
            load_error: string | null;
            meta: components["schemas"]["MetaOut"];
            /** Raw Pivots */
            raw_pivots: components["schemas"]["PivotOut"][];
            report: components["schemas"]["ReportOut"] | null;
            scenario_counts: components["schemas"]["ScenarioCountsOut"];
            selected_anchor: components["schemas"]["PivotOut"] | null;
            top_scenario: components["schemas"]["ScenarioOut"] | null;
            top_scenario_layer1: components["schemas"]["Layer1Response"] | null;
        };
        /** PivotOut */
        PivotOut: {
            /** Bar Index */
            bar_index: number | null;
            /** Index */
            index: number;
            /** Kind */
            kind: string;
            /** Price */
            price: number;
            /** Time */
            time: string;
        };
        /** PriceMoveOut */
        PriceMoveOut: {
            /** Label */
            label: string;
            /** Pct From Current */
            pct_from_current: number;
            /** Price */
            price: number;
        };
        /**
         * QaChartContext
         * @description Pipeline params + scenario_id: reconstructs the chart the user is looking at.
         */
        QaChartContext: {
            /**
             * Atr Floor
             * @default 0.1
             */
            atr_floor: number;
            /**
             * Atr Multiplier
             * @default 3
             */
            atr_multiplier: number;
            /**
             * Atr Period
             * @default 14
             */
            atr_period: number;
            /**
             * Commitment Curve
             * @default linear
             * @enum {string}
             */
            commitment_curve: "linear" | "sqrt" | "off";
            /**
             * K Sigma
             * @default 0.5
             */
            k_sigma: number;
            /**
             * Log Tol Fib
             * @default 0.05
             */
            log_tol_fib: number;
            /**
             * Min Bars Between
             * @default 4
             */
            min_bars_between: number;
            /**
             * Period
             * @default max
             * @enum {string}
             */
            period: "2y" | "5y" | "10y" | "max";
            /**
             * Pivot Window
             * @default 2
             */
            pivot_window: number;
            /**
             * Pull Depth Hi
             * @default 0.618
             */
            pull_depth_hi: number;
            /**
             * Pull Depth Lo
             * @default 0.382
             */
            pull_depth_lo: number;
            /**
             * Pull Depth Tol
             * @default 0.15
             */
            pull_depth_tol: number;
            /**
             * Scale Mode
             * @default linear
             * @enum {string}
             */
            scale_mode: "linear" | "log";
            /**
             * Scenario Id
             * @description Scenario.id from /api/pipeline response
             */
            scenario_id: string;
            /**
             * Symbol
             * @description Ticker symbol (yfinance compatible)
             * @default DDOG
             */
            symbol: string;
            /**
             * Timeframe
             * @default week
             * @enum {string}
             */
            timeframe: "day" | "week" | "month";
        };
        /** QaCitation */
        QaCitation: {
            /** Claim Sentence */
            claim_sentence: string;
            /** Page */
            page: number;
        };
        /**
         * QaRequest
         * @description chart optional: when set, its params reconstruct that chart for chart-aware
         *     answers; when omitted, the answer is pure theory RAG.
         */
        QaRequest: {
            /** @description optional chart context for chart-aware Q&A */
            chart?: components["schemas"]["QaChartContext"] | null;
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
            /** Question */
            question: string;
        };
        /** QaResponse */
        QaResponse: {
            /** Answer */
            answer: string;
            /** Cached */
            cached: boolean;
            /** Citations */
            citations: components["schemas"]["QaCitation"][];
            /** Fell Back */
            fell_back: boolean;
            /** Model Id */
            model_id: string | null;
            /** Out Of Scope */
            out_of_scope: boolean;
            /** Question */
            question: string;
            /** Retrieved Pages */
            retrieved_pages: number[];
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Analyst Prewarmed */
            analyst_prewarmed: boolean;
            /** Qa Enabled */
            qa_enabled: boolean;
            /** Status */
            status: string;
        };
        /** ReportOut */
        ReportOut: {
            anchor: components["schemas"]["PivotOut"] | null;
            diagnostic: components["schemas"]["DiagnosticOut"] | null;
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioOut"][];
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /** Summary */
            summary: string;
        };
        /** ScenarioCountsOut */
        ScenarioCountsOut: {
            /** Complete */
            complete: number;
            /** Open */
            open: number;
            /** Total */
            total: number;
        };
        /** ScenarioOut */
        ScenarioOut: {
            confidence_tier: components["schemas"]["ConfidenceTierOut"];
            /** Depth */
            depth: number;
            /** Family */
            family: string;
            /** Family Label */
            family_label: string;
            /** Id */
            id: string;
            /** Is Complete */
            is_complete: boolean;
            open_subtree: components["schemas"]["WaveOut"] | null;
            /** Pattern Kind */
            pattern_kind: string | null;
            /** Pattern Label */
            pattern_label: string | null;
            root: components["schemas"]["WaveOut"];
            /** Score */
            score: number;
            /** Score Components */
            score_components: {
                [key: string]: number;
            };
        };
        /** SegmentOut */
        SegmentOut: {
            end: components["schemas"]["PivotOut"];
            start: components["schemas"]["PivotOut"];
        };
        /** StartFrame */
        StartFrame: {
            /** Mode */
            mode: string;
            /** Model Id */
            model_id: string | null;
            /** Scenario Id */
            scenario_id: string;
        };
        /** SuccessionReportOut */
        SuccessionReportOut: {
            /** Family */
            family: string;
            /** Is Terminal */
            is_terminal: boolean;
            /** Next Patterns */
            next_patterns: components["schemas"]["NextPatternOut"][];
            /** Note */
            note: string;
        };
        /** TargetOut */
        TargetOut: {
            /** Derivation */
            derivation: string;
            /** Name */
            name: string;
            /** Price */
            price: number;
            /** Theory Page */
            theory_page: number;
            /** Type */
            type: string;
        };
        /** TargetSetOut */
        TargetSetOut: {
            /** Confirmation Targets */
            confirmation_targets: components["schemas"]["TargetOut"][];
            /** Fib Flow Targets */
            fib_flow_targets: components["schemas"]["TargetOut"][];
            invalidation: components["schemas"]["TargetOut"];
        };
        /** TheoryRefOut */
        TheoryRefOut: {
            /** Binding */
            binding: string;
            /** Concept */
            concept: string;
            /** Note */
            note: string;
            /** Pages */
            pages: number[];
        };
        /** TokenFrame */
        TokenFrame: {
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WaveOut */
        WaveOut: {
            /** Children */
            children: components["schemas"]["WaveOut"][];
            /** Degree Label */
            degree_label: string | null;
            /** Nesting Level */
            nesting_level: number;
            /** Pattern Kind */
            pattern_kind: string | null;
            /** Role */
            role: string;
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /** Sets */
            sets: components["schemas"]["LinkSetOut"][] | null;
            span_end: components["schemas"]["PivotOut"] | null;
            span_start: components["schemas"]["PivotOut"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    analyst_stream_api_v1_analyst_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalystStreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_api_v1_pipeline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    qa_api_v1_qa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_education_api_v1_scenario_education_get: {
        parameters: {
            query: {
                family: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EducationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_layer1_api_v1_scenario_layer1_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Layer1Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer1Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
